### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bb1950328** [Jungwacht-Herisau/chlauseditor#22]
- [ ] Router-URL Problem auf GitHub Pages
- [ ] Popup ist beim Verschieben von Tour-Elementen im Weg
- [ ] Option machen, die Startzeit des Elements manuell einzugeben
- [ ] Verwaiste Popups, wenn Element gelöscht wird
- [ ] Elemente landen manchmal am falschen Ort, wenn sie nur ein bisschen verschoben werden
